<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Payment Status Export</title>
    <style>
        body { font-family: 'Helvetica', sans-serif; font-size: 11px; color: #333; margin: 0; padding: 0; }
        
        .header { 
            background-color: #2c3e50; 
            color: #fff; 
            padding: 20px; 
            text-align: center;
            margin-bottom: 20px;
        }
        .school-name { font-size: 24px; font-weight: bold; text-transform: uppercase; letter-spacing: 1px; }
        .report-title { font-size: 16px; margin-top: 5px; opacity: 0.9; }
        .meta-info { font-size: 10px; margin-top: 5px; opacity: 0.7; }

        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th, td { padding: 10px; text-align: left; border-bottom: 1px solid #ddd; }
        th { 
            background-color: #f8f9fa; 
            font-weight: bold; 
            text-transform: uppercase; 
            font-size: 10px; 
            color: #555;
            border-top: 2px solid #2c3e50;
        }
        tr:nth-child(even) { background-color: #f9f9f9; }

        .status-pill {
            display: inline-block;
            padding: 3px 8px;
            font-size: 10px;
            font-weight: bold;
            border-radius: 12px;
            text-transform: uppercase;
        }
        .status-paid { background-color: #e6fffa; color: #276749; border: 1px solid #276749; }
        .status-unpaid { background-color: #fff5f5; color: #c53030; border: 1px solid #c53030; }
        .status-partial { background-color: #fffaf0; color: #c05621; border: 1px solid #c05621; }
        .status-overdue { background-color: #fff5f5; color: #9b2c2c; border: 1px solid #9b2c2c; }
        
        .footer {
            position: fixed;
            bottom: 0;
            left: 0;
            right: 0;
            padding: 10px;
            text-align: center;
            font-size: 9px;
            color: #777;
            border-top: 1px solid #eee;
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="school-name">{{ config('app.name', 'Oromex School') }}</div>
        <div class="report-title">{{ $title }}</div>
        <div class="meta-info">Generated on: {{ now()->format('F j, Y, g:i a') }}</div>
    </div>

    <div class="footer">
        Confidential Document - For Administrative Use Only - Generated by Oromex School System
    </div>

    <table>
        <thead>
            <tr>
                <th style="width: 25%;">Student Name</th>
                <th style="width: 15%;">Grade/Section</th>
                <th style="width: 15%;">Amount</th>
                <th style="width: 15%;">Status</th>
                <th style="width: 20%;">Date</th>
            </tr>
        </thead>
        <tbody>
            @forelse($payments as $payment)
                <tr>
                    <td><strong>{{ $payment->student->user->name }}</strong></td>
                    <td>{{ $payment->student->grade->name }} / {{ $payment->student->section->name }}</td>
                    <td>{{ number_format($payment->amount, 2) }}</td>
                    <td>
                        <span class="status-pill status-{{ strtolower($payment->status) }}">
                            {{ ucfirst($payment->status) }}
                        </span>
                    </td>
                    <td>{{ $payment->created_at->format('Y-m-d') }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="5" style="text-align: center; padding: 30px; color: #777;">
                        No payment records found.
                    </td>
                </tr>
            @endforelse
        </tbody>
    </table>
</body>
</html>
