<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Rank List Export</title>
    <style>
        body { font-family: 'Helvetica', sans-serif; font-size: 11px; color: #333; margin: 0; padding: 0; }
        
        .header { 
            background-color: #2c3e50; 
            color: #fff; 
            padding: 20px; 
            text-align: center;
            margin-bottom: 20px;
        }
        .school-name { font-size: 24px; font-weight: bold; text-transform: uppercase; letter-spacing: 1px; }
        .report-title { font-size: 16px; margin-top: 5px; opacity: 0.9; }
        .meta-info { font-size: 10px; margin-top: 5px; opacity: 0.7; }

        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th, td { padding: 10px; text-align: left; border-bottom: 1px solid #ddd; }
        th { 
            background-color: #f8f9fa; 
            font-weight: bold; 
            text-transform: uppercase; 
            font-size: 10px; 
            color: #555;
            border-top: 2px solid #2c3e50;
        }
        tr:nth-child(even) { background-color: #f9f9f9; }

        .rank-badge { 
            display: inline-block; width: 24px; height: 24px; 
            line-height: 24px; text-align: center; border-radius: 50%; 
            font-weight: bold; font-size: 11px;
        }
        .rank-1 { background-color: #FFD700; color: #000; box-shadow: 0 2px 2px rgba(0,0,0,0.1); }
        .rank-2 { background-color: #C0C0C0; color: #000; box-shadow: 0 2px 2px rgba(0,0,0,0.1); }
        .rank-3 { background-color: #CD7F32; color: #fff; box-shadow: 0 2px 2px rgba(0,0,0,0.1); }
        
        .footer {
            position: fixed;
            bottom: 0;
            left: 0;
            right: 0;
            padding: 10px;
            text-align: center;
            font-size: 9px;
            color: #777;
            border-top: 1px solid #eee;
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="school-name">{{ config('app.name', 'Oromex School') }}</div>
        <div class="report-title">{{ $title }}</div>
        <div class="meta-info">Generated on: {{ now()->format('F j, Y, g:i a') }}</div>
    </div>

    <div class="footer">
        Confidential Document - For Administrative Use Only - Generated by Oromex School System
    </div>

    <table>
        <thead>
            <tr>
                <th style="width: 10%; text-align: center;">Rank</th>
                <th style="width: 15%;">Student ID</th>
                <th>Name</th>
                <th style="width: 15%; text-align: center;">Average (%)</th>
            </tr>
        </thead>
        <tbody>
            @forelse($rankedStudents as $item)
                <tr>
                    <td style="text-align: center;">
                        @if($item['rank'] == 1) <span class="rank-badge rank-1">1</span>
                        @elseif($item['rank'] == 2) <span class="rank-badge rank-2">2</span>
                        @elseif($item['rank'] == 3) <span class="rank-badge rank-3">3</span>
                        @else <strong>{{ $item['rank'] }}</strong>
                        @endif
                    </td>
                    <td>{{ $item['student']->student_id }}</td>
                    <td>{{ $item['student']->user->name }}</td>
                    <td style="text-align: center; font-weight: bold; color: #2c3e50;">
                        {{ number_format($item['average'], 2) }}%
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="4" style="text-align: center; padding: 30px; color: #777;">
                        No ranking data found for this selection.
                    </td>
                </tr>
            @endforelse
        </tbody>
    </table>
</body>
</html>
