<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Student List Export</title>
    <style>
        body { font-family: 'Helvetica', sans-serif; font-size: 11px; color: #333; margin: 0; padding: 0; }
        
        .header { 
            background-color: #2c3e50; 
            color: #fff; 
            padding: 20px; 
            text-align: center;
            margin-bottom: 20px;
        }
        .school-name { font-size: 24px; font-weight: bold; text-transform: uppercase; letter-spacing: 1px; }
        .report-title { font-size: 16px; margin-top: 5px; opacity: 0.9; }
        .meta-info { font-size: 10px; margin-top: 5px; opacity: 0.7; }

        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th, td { padding: 10px; text-align: left; border-bottom: 1px solid #ddd; }
        th { 
            background-color: #f8f9fa; 
            font-weight: bold; 
            text-transform: uppercase; 
            font-size: 10px; 
            color: #555;
            border-top: 2px solid #2c3e50;
        }
        tr:nth-child(even) { background-color: #f9f9f9; }
        
        .footer {
            position: fixed;
            bottom: 0;
            left: 0;
            right: 0;
            padding: 10px;
            text-align: center;
            font-size: 9px;
            color: #777;
            border-top: 1px solid #eee;
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="school-name">{{ config('app.name', 'Oromex School') }}</div>
        <div class="report-title">{{ $title }}</div>
        <div class="meta-info">Generated on: {{ now()->format('F j, Y, g:i a') }}</div>
    </div>

    <div class="footer">
        Confidential Document - For Administrative Use Only - Generated by Oromex School System
    </div>

    <table>
        <thead>
            <tr>
                <th style="width: 20%;">Student ID</th>
                <th>Name</th>
                <th style="width: 15%;">Grade</th>
                <th style="width: 15%;">Section</th>
            </tr>
        </thead>
        <tbody>
            @forelse($students as $student)
                <tr>
                    <td><strong>{{ $student->student_id }}</strong></td>
                    <td>{{ $student->user?->name ?? 'N/A' }}</td>
                    <td>{{ $student->grade?->name }}</td>
                    <td>{{ $student->section?->name }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="4" style="text-align: center; padding: 30px; color: #777;">
                        No students found matching the criteria.
                    </td>
                </tr>
            @endforelse
        </tbody>
    </table>
</body>
</html>
